<?php

namespace Database\Seeders;

use App\Models\Prospect;
use Illuminate\Database\Seeder;

/**
 * GO_CHILE_PROSPECTOS_ECLIPSE_2027.md/.csv — 31 prospectos de Futaleufú
 * para el Eclipse Solar Anular del 6 de febrero de 2027 (Futaleufú está
 * dentro de la franja de anularidad). Fuente: directorio oficial de la
 * Municipalidad de Futaleufú.
 *
 * Idempotente por business_name (updateOrCreate).
 *
 * Mismo criterio que ProspectosRmSeeder: "Por verificar"/"— confirmar" en
 * whatsapp/email/instagram/website no se carga como texto placeholder —
 * queda null y la advertencia se suma a notes. Cuando la fuente trae un
 * segundo teléfono además del WhatsApp principal, ese número extra
 * también va a notes en vez de perderse.
 */
class ProspectosEclipse2027Seeder extends Seeder
{
    public function run(): void
    {
        $prospects = [
            [
                'business_name' => 'Patagonia Elements',
                'contact_name' => null,
                'territory' => 'Futaleufú / Provincia de Palena',
                'category' => 'Rafting, kayak y flotadas',
                'whatsapp' => '+56 9 7744 7250',
                'email' => 'info@patagoniaelements.com',
                'instagram' => null,
                'website' => 'https://www.patagoniaelements.com',
                'observed_problem' => 'Tiene presencia digital; oportunidad en ficha Eclipse 2027, paquetes y agenda',
                'source' => 'Directorio oficial Municipalidad de Futaleufú',
                'notes' => 'Operador oficial del destino. Instagram y persona de contacto por verificar/identificar.',
            ],
            [
                'business_name' => 'Condor Fu',
                'contact_name' => 'Vanessa — confirmar',
                'territory' => 'Futaleufú / Provincia de Palena',
                'category' => 'Rafting, kayak y turismo aventura',
                'whatsapp' => '+56 9 4213 9636',
                'email' => 'vanessa@condorfu.cl',
                'instagram' => null,
                'website' => 'https://www.condorfu.cl',
                'observed_problem' => 'Tiene web; oportunidad en experiencia Eclipse + aventura',
                'source' => 'Directorio oficial Municipalidad de Futaleufú',
                'notes' => 'Confirmar persona de contacto. Instagram por verificar.',
            ],
            [
                'business_name' => 'Bochinche Expediciones',
                'contact_name' => null,
                'territory' => 'Futaleufú / Provincia de Palena',
                'category' => 'Rafting y expediciones',
                'whatsapp' => '+56 9 3392 0745',
                'email' => 'bochinchex@gmail.com',
                'instagram' => null,
                'website' => 'https://www.bochinchex.com',
                'observed_problem' => 'Tiene web; oportunidad en paquetes especiales y agenda Eclipse',
                'source' => 'Directorio oficial Municipalidad de Futaleufú',
                'notes' => 'Reconfirmar contacto. Teléfono alternativo: +56 9 3392 0744. Instagram y persona de contacto por verificar/identificar.',
            ],
            [
                'business_name' => 'World Patagonia',
                'contact_name' => null,
                'territory' => 'Futaleufú / Provincia de Palena',
                'category' => 'Rafting y turismo aventura',
                'whatsapp' => '+56 9 8325 9482',
                'email' => 'contacto@worldpatagonia.com',
                'instagram' => null,
                'website' => 'https://www.worldpatagonia.com',
                'observed_problem' => 'Tiene web; oportunidad en campaña Eclipse y experiencias combinadas',
                'source' => 'Directorio oficial Municipalidad de Futaleufú',
                'notes' => 'Reconfirmar datos. Instagram y persona de contacto por verificar/identificar.',
            ],
            [
                'business_name' => 'Río Futaleufú Rafting',
                'contact_name' => null,
                'territory' => 'Futaleufú / Provincia de Palena',
                'category' => 'Rafting',
                'whatsapp' => '+56 9 6528 7716',
                'email' => 'riofutaleufurafting@gmail.com',
                'instagram' => null,
                'website' => 'https://www.riofutaleufu.com',
                'observed_problem' => 'Tiene web; oportunidad en paquete Eclipse + rafting',
                'source' => 'Directorio oficial Municipalidad de Futaleufú',
                'notes' => 'Negocio con presencia pública actual. Instagram y persona de contacto por verificar/identificar.',
            ],
            [
                'business_name' => 'Rafting Futaleufú',
                'contact_name' => null,
                'territory' => 'Futaleufú / Provincia de Palena',
                'category' => 'Rafting',
                'whatsapp' => '+56 9 8570 2407',
                'email' => 'raftingoutdoor@gmail.com',
                'instagram' => null,
                'website' => 'https://www.raftingfutaleufu.cl',
                'observed_problem' => 'Tiene web; oportunidad en experiencia Eclipse y agenda',
                'source' => 'Directorio oficial Municipalidad de Futaleufú',
                'notes' => 'Reconfirmar disponibilidad para febrero 2027. Instagram y persona de contacto por verificar/identificar.',
            ],
            [
                'business_name' => 'Futaleufú Outdoor Center',
                'contact_name' => null,
                'territory' => 'Futaleufú / Río El Azul',
                'category' => 'Turismo aventura / outdoor',
                'whatsapp' => '+56 9 6201 4158',
                'email' => 'futaleufuoutdoorcenter@hotmail.com',
                'instagram' => null,
                'website' => 'https://www.discoverpatagonia.net',
                'observed_problem' => 'Presencia digital; oportunidad en miradores, actividades y campaña Eclipse',
                'source' => 'Directorio oficial Municipalidad de Futaleufú',
                'notes' => 'Sector Río El Azul. Instagram y persona de contacto por verificar/identificar.',
            ],
            [
                'business_name' => 'Path Patagonia',
                'contact_name' => null,
                'territory' => 'Futaleufú / El Azul',
                'category' => 'Turismo aventura / expediciones',
                'whatsapp' => '+56 9 8360 1747',
                'email' => 'info@pathpatagonia.com',
                'instagram' => null,
                'website' => 'https://www.pathpatagonia.com',
                'observed_problem' => 'Tiene web; oportunidad en trekking, miradores y experiencias Eclipse',
                'source' => 'Directorio oficial Municipalidad de Futaleufú',
                'notes' => 'Sector El Azul. Instagram y persona de contacto por verificar/identificar.',
            ],
            [
                'business_name' => 'Cara del Indio',
                'contact_name' => null,
                'territory' => 'Futaleufú / El Azul',
                'category' => 'Turismo y alojamiento',
                'whatsapp' => '+56 9 7468 1573',
                'email' => 'caradelindiofutaleufu@gmail.com',
                'instagram' => null,
                'website' => 'https://www.caradelindio.cl',
                'observed_problem' => 'Puede combinar alojamiento, naturaleza y observación del eclipse',
                'source' => 'Directorio oficial Municipalidad de Futaleufú',
                'notes' => 'También aparece en directorio de alojamiento. Instagram y persona de contacto por verificar/identificar.',
            ],
            [
                'business_name' => 'Earth River Expeditions',
                'contact_name' => null,
                'territory' => 'Futaleufú / Río El Azul',
                'category' => 'Rafting y expediciones',
                'whatsapp' => '+56 9 9828 2399',
                'email' => 'info@earthriver.com',
                'instagram' => null,
                'website' => 'https://www.earthriver.com',
                'observed_problem' => 'Operador con potencial para producto premium Eclipse + expedición',
                'source' => 'Directorio oficial Municipalidad de Futaleufú',
                'notes' => 'Reconfirmar datos. Instagram y persona de contacto por verificar/identificar.',
            ],
            [
                'business_name' => 'Futaleufú Expediciones Rafting',
                'contact_name' => null,
                'territory' => 'Futaleufú',
                'category' => 'Rafting / expediciones',
                'whatsapp' => '+56 9 8786 1184',
                'email' => null,
                'instagram' => '@futaleufuexpediciones',
                'website' => null,
                'observed_problem' => 'Presencia en redes; oportunidad para ficha GO Eclipse y agenda',
                'source' => 'Directorio oficial Municipalidad de Futaleufú',
                'notes' => 'Instagram publicado por municipio. Email, sitio web y persona de contacto por verificar/identificar.',
            ],
            [
                'business_name' => 'Turismo Antuhuya',
                'contact_name' => null,
                'territory' => 'Futaleufú / Lago Espolón',
                'category' => 'Cabalgatas y turismo rural',
                'whatsapp' => '+56 9 6101 4061',
                'email' => 'turismo.antuhuya@gmail.com',
                'instagram' => null,
                'website' => 'https://www.turismoantuhuya.cl',
                'observed_problem' => 'Experiencia rural ideal para complementar el programa Eclipse',
                'source' => 'Directorio oficial Municipalidad de Futaleufú',
                'notes' => 'Reconfirmar disponibilidad. Teléfono alternativo: +56 9 5861 9947. Instagram y persona de contacto por verificar/identificar.',
            ],
            [
                'business_name' => 'Agroturismo Cerro La Bandera',
                'contact_name' => null,
                'territory' => 'Futaleufú / Noroeste',
                'category' => 'Cabalgatas y turismo rural',
                'whatsapp' => '+56 9 3275 8735',
                'email' => 'cabalgatascerrolabandera@gmail.com',
                'instagram' => null,
                'website' => null,
                'observed_problem' => 'Oportunidad para cabalgata + observación Eclipse',
                'source' => 'Directorio oficial Municipalidad de Futaleufú',
                'notes' => 'Turismo rural. Instagram, sitio web y persona de contacto por verificar/identificar.',
            ],
            [
                'business_name' => 'Agroturismo Los 3 Morros',
                'contact_name' => null,
                'territory' => 'Futaleufú / El Espolón',
                'category' => 'Turismo rural y cabalgatas',
                'whatsapp' => '+56 9 3207 6560',
                'email' => 'turismo3morros@gmail.com',
                'instagram' => '@turismotresmorros',
                'website' => null,
                'observed_problem' => 'Oportunidad para experiencia rural, gastronomía y Eclipse',
                'source' => 'Directorio oficial Municipalidad de Futaleufú',
                'notes' => 'Reconfirmar contacto. Sitio web por verificar. Persona de contacto por identificar.',
            ],
            [
                'business_name' => 'Centro de Aventuras Lonconao',
                'contact_name' => 'Eliseo Leal — confirmar',
                'territory' => 'Futaleufú / Lonconao',
                'category' => 'Trekking y aventura',
                'whatsapp' => '+56 9 9237 8684',
                'email' => 'eliseoleal@yahoo.es',
                'instagram' => null,
                'website' => null,
                'observed_problem' => 'Ideal para trekking a miradores y experiencia Eclipse',
                'source' => 'Directorio oficial Municipalidad de Futaleufú',
                'notes' => 'Confirmar persona de contacto. Instagram y sitio web por verificar.',
            ],
            [
                'business_name' => 'Futaleufu Nativo Expediciones',
                'contact_name' => null,
                'territory' => 'Futaleufú',
                'category' => 'Trekking y expediciones',
                'whatsapp' => '+56 9 7391 0734',
                'email' => 'futaleufunativoex@gmail.com',
                'instagram' => '@futaleufu_nativo',
                'website' => null,
                'observed_problem' => 'Potencial para trekking, miradores y contenido Eclipse',
                'source' => 'Directorio oficial Municipalidad de Futaleufú',
                'notes' => 'Instagram publicado por municipio. Sitio web por verificar. Persona de contacto por identificar.',
            ],
            [
                'business_name' => 'Agroturismo Los 3 Amigos',
                'contact_name' => null,
                'territory' => 'Futaleufú / Las Escalas',
                'category' => 'Turismo rural y navegación',
                'whatsapp' => '+56 9 9420 9594',
                'email' => 'alberguelostresamigos@gmail.com',
                'instagram' => null,
                'website' => 'https://www.lostresamigosfuta.wordpress.com',
                'observed_problem' => 'Puede integrar alojamiento, navegación y experiencia rural Eclipse',
                'source' => 'Directorio oficial Municipalidad de Futaleufú',
                'notes' => 'Reconfirmar oferta actual. Instagram y persona de contacto por verificar/identificar.',
            ],
            [
                'business_name' => 'Agroturismo Lago Las Rosas',
                'contact_name' => null,
                'territory' => 'Futaleufú / Lago Las Rosas',
                'category' => 'Turismo rural',
                'whatsapp' => '+56 9 8385 6804',
                'email' => null,
                'instagram' => null,
                'website' => null,
                'observed_problem' => 'Oportunidad para experiencia rural y observación Eclipse',
                'source' => 'Directorio oficial Municipalidad de Futaleufú',
                'notes' => 'Reconfirmar datos. Teléfono alternativo: +56 9 8971 4031. Email, sitio web, Instagram y persona de contacto por verificar/identificar.',
            ],
            [
                'business_name' => 'Agroturismo Futaleufú',
                'contact_name' => 'Alexis — confirmar',
                'territory' => 'Futaleufú / Lago Espolón',
                'category' => 'Agroturismo y alojamiento',
                'whatsapp' => '+56 9 7631 0608',
                'email' => 'alexis_espolon@hotmail.com',
                'instagram' => '@agroturismofutaleufu',
                'website' => 'https://agroturismofutaleufu.cl',
                'observed_problem' => 'Puede ofrecer experiencia rural y alojamiento para visitantes del Eclipse',
                'source' => 'Directorio oficial Municipalidad de Futaleufú',
                'notes' => 'Confirmar persona.',
            ],
            [
                'business_name' => 'Red de las Delicias',
                'contact_name' => null,
                'territory' => 'Futaleufú / El Límite',
                'category' => 'Gastronomía y producción local',
                'whatsapp' => '+56 9 6100 1872',
                'email' => 'reddelasdelicias@gmail.com',
                'instagram' => '@red_de_las_delicias_futa',
                'website' => null,
                'observed_problem' => 'Oportunidad para gastronomía local asociada a campaña Eclipse',
                'source' => 'Directorio oficial Municipalidad de Futaleufú',
                'notes' => 'Puede funcionar como aliado gastronómico. Sitio web por verificar. Persona de contacto por identificar.',
            ],
            [
                'business_name' => 'Cabañas Aitue',
                'contact_name' => null,
                'territory' => 'Futaleufú',
                'category' => 'Alojamiento / cabañas',
                'whatsapp' => '+56 9 8861 0980',
                'email' => 'aituefutaleufu@gmail.com',
                'instagram' => null,
                'website' => 'https://www.cabañasaitue.cl/',
                'observed_problem' => 'Alta relevancia por demanda de alojamiento; oportunidad para ficha Eclipse',
                'source' => 'Directorio oficial de alojamiento Municipalidad de Futaleufú',
                'notes' => 'Confirmar disponibilidad febrero 2027. Instagram y persona de contacto por verificar/identificar.',
            ],
            [
                'business_name' => 'Cabañas El Maitén',
                'contact_name' => 'Eliana Pinilla — confirmar',
                'territory' => 'Futaleufú',
                'category' => 'Alojamiento / cabañas',
                'whatsapp' => '+56 9 9085 6426',
                'email' => 'eliana.pinilla@cabanaselmaiten.cl',
                'instagram' => null,
                'website' => 'https://cabanaselmaiten.cl',
                'observed_problem' => 'Oportunidad para reservas y visibilidad específica Eclipse',
                'source' => 'Directorio oficial de alojamiento Municipalidad de Futaleufú',
                'notes' => 'Confirmar contacto. Instagram por verificar.',
            ],
            [
                'business_name' => 'Cabañas Aguas Blancas',
                'contact_name' => null,
                'territory' => 'Futaleufú',
                'category' => 'Alojamiento / cabañas',
                'whatsapp' => '+56 9 9452 3073',
                'email' => 'cabanasaguasblancas@gmail.com',
                'instagram' => '@cabanasaguasblancas',
                'website' => null,
                'observed_problem' => 'Oportunidad para alojamiento Eclipse y ficha GO',
                'source' => 'Directorio oficial de alojamiento Municipalidad de Futaleufú',
                'notes' => 'Instagram publicado por municipio. Sitio web por verificar. Persona de contacto por identificar.',
            ],
            [
                'business_name' => 'Refugio Los Cipreses',
                'contact_name' => null,
                'territory' => 'Futaleufú / Río Chico',
                'category' => 'Hotel / refugio',
                'whatsapp' => '+56 9 8662 2150',
                'email' => null,
                'instagram' => null,
                'website' => 'https://www.refugioloscipreses.cl',
                'observed_problem' => 'Alojamiento con potencial para visitantes del Eclipse',
                'source' => 'Directorio oficial de alojamiento Municipalidad de Futaleufú',
                'notes' => 'Reconfirmar datos. Email, Instagram y persona de contacto por verificar/identificar.',
            ],
            [
                'business_name' => 'PATA Lodge',
                'contact_name' => null,
                'territory' => 'Futaleufú / Las Escalas',
                'category' => 'Lodge / alojamiento',
                'whatsapp' => '+56 9 7955 9817',
                'email' => null,
                'instagram' => null,
                'website' => 'https://www.pata.cl',
                'observed_problem' => 'Potencial producto premium de alojamiento + Eclipse',
                'source' => 'Directorio oficial de alojamiento Municipalidad de Futaleufú',
                'notes' => 'Reconfirmar disponibilidad. Email, Instagram y persona de contacto por verificar/identificar.',
            ],
            [
                'business_name' => 'Peuma Lodge',
                'contact_name' => null,
                'territory' => 'Futaleufú',
                'category' => 'Lodge / alojamiento',
                'whatsapp' => '+56 9 8353 0202',
                'email' => null,
                'instagram' => null,
                'website' => 'https://www.peumalodge.com',
                'observed_problem' => 'Potencial para visitantes de alto interés y experiencia Eclipse',
                'source' => 'Directorio oficial de alojamiento Municipalidad de Futaleufú',
                'notes' => 'Reconfirmar datos. Email, Instagram y persona de contacto por verificar/identificar.',
            ],
            [
                'business_name' => 'Futa Lodge',
                'contact_name' => null,
                'territory' => 'Futaleufú / Las Escalas',
                'category' => 'Lodge / alojamiento',
                'whatsapp' => '+56 9 8595 0064',
                'email' => null,
                'instagram' => null,
                'website' => 'https://www.futalodge.com',
                'observed_problem' => 'Alojamiento relevante para campaña Eclipse',
                'source' => 'Directorio oficial de alojamiento Municipalidad de Futaleufú',
                'notes' => 'Reconfirmar disponibilidad. Email, Instagram y persona de contacto por verificar/identificar.',
            ],
            [
                'business_name' => 'Hostería Futaleufú',
                'contact_name' => null,
                'territory' => 'Futaleufú',
                'category' => 'Hostería / alojamiento',
                'whatsapp' => '+56 9 5062 0081',
                'email' => null,
                'instagram' => null,
                'website' => 'https://www.hosteriafutaleufu.cl',
                'observed_problem' => 'Alojamiento céntrico; oportunidad para captar demanda Eclipse',
                'source' => 'Directorio oficial de alojamiento Municipalidad de Futaleufú',
                'notes' => 'Reconfirmar disponibilidad. Email, Instagram y persona de contacto por verificar/identificar.',
            ],
            [
                'business_name' => 'Antigua Casona',
                'contact_name' => null,
                'territory' => 'Futaleufú',
                'category' => 'Hotel / hostería',
                'whatsapp' => '+56 9 8476 4480',
                'email' => null,
                'instagram' => null,
                'website' => 'https://www.antiguacasona.cl',
                'observed_problem' => 'Alojamiento con potencial para demanda anticipada del Eclipse',
                'source' => 'Directorio oficial de alojamiento Municipalidad de Futaleufú',
                'notes' => 'Reconfirmar disponibilidad. Email, Instagram y persona de contacto por verificar/identificar.',
            ],
            [
                'business_name' => 'El Barranco',
                'contact_name' => null,
                'territory' => 'Futaleufú',
                'category' => 'Hotel / hostería',
                'whatsapp' => '+56 65 2721 314',
                'email' => null,
                'instagram' => null,
                'website' => 'https://www.elbarrancochile.cl',
                'observed_problem' => 'Alojamiento con oportunidad de posicionamiento Eclipse',
                'source' => 'Directorio oficial de alojamiento Municipalidad de Futaleufú',
                'notes' => 'Reconfirmar disponibilidad. Email, Instagram y persona de contacto por verificar/identificar.',
            ],
            [
                'business_name' => 'Sierra Huacha',
                'contact_name' => null,
                'territory' => 'Futaleufú',
                'category' => 'Cabañas / alojamiento',
                'whatsapp' => '+56 65 2721 473',
                'email' => 'sierrahuacha@gmail.com',
                'instagram' => null,
                'website' => 'https://www.sierrahuacha.cl',
                'observed_problem' => 'Oportunidad de captar reservas Eclipse y aparecer en mapa GO',
                'source' => 'Directorio oficial de alojamiento Municipalidad de Futaleufú',
                'notes' => 'Reconfirmar datos. Instagram y persona de contacto por verificar/identificar.',
            ],
        ];

        foreach ($prospects as $data) {
            Prospect::updateOrCreate(
                ['business_name' => $data['business_name']],
                $data + ['status' => 'prospecto']
            );
        }
    }
}
